### ISSUE TITLE
Spotify: Only personally created playlists are shown

### ISSUE THREAD

**Issue by C4lopsitta** [tvillarete/ipod-classic-js#35] opened 2021-06-24 10:19 UTC
With Spotify only half of the playlist are shown

**Comment by tvillarete** [comment] 2021-06-25 02:38
Hey @C4lopsitta, this is most likely due to a slightly incorrect API request I'm making. Currently it only displays playlists that the logged-in user has created, not every playlist in your library. I'll see if I can file a fix for it. Thanks!

**Comment by tvillarete** [comment] 2021-07-02 05:24
I was able to figure out the root cause of this issue. Turns out I needed to ask for extra permissions to view all user playlists – specifically these additional scopes:

- `playlist-read-private`
- `playlist-read-collaborative`

Once you sign out and then sign in again, it'll ask you to re-authorize and then you should see _all_ your followed playlists. Thanks for bringing this up! Closing this issue now

**Closed as completed by tvillarete** 2021-07-02 05:24 UTC
Labels: bug, fixed
